author: AzaToth
database: false
description: "Reduce drop rates depending on how much damage the final player made; Based on NoFarm by McSpazzy and Jadewolf"
main: se.azatoth.properreward.ProperReward
name: ProperReward
version: '0.1'
authors:
  - McSpazzy
    - Jadedwolf
      - AzaToth
